serviceMaps:
  serviceName: pet-services
  mappings:
    - version: 1.0
      description: Persists Pet details in tables
      fromTopic: save-ptr-application
      isTransaction: true	
      queryMaps:

        - query: INSERT INTO eg_ptr_registration(id,tenantid,applicationnumber,applicantName,fathername,mobileNumber,emailId,applicationType,validityDate,status,expireFlag,petToken,previousApplicationNumber,propertyId,createdby,lastmodifiedby,createdtime,lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.id

            - jsonPath: $.PetRegistrationApplications.*.tenantId

            - jsonPath: $.PetRegistrationApplications.*.applicationNumber
            
            - jsonPath: $.PetRegistrationApplications.*.applicantName
          
            - jsonPath: $.PetRegistrationApplications.*.fatherName
            
            - jsonPath: $.PetRegistrationApplications.*.mobileNumber
            
            - jsonPath: $.PetRegistrationApplications.*.emailId
            
            - jsonPath: $.PetRegistrationApplications.*.applicationType

            - jsonPath: $.PetRegistrationApplications.*.validityDate

            - jsonPath: $.PetRegistrationApplications.*.status

            - jsonPath: $.PetRegistrationApplications.*.expireFlag

            - jsonPath: $.PetRegistrationApplications.*.petToken

            - jsonPath: $.PetRegistrationApplications.*.previousApplicationNumber
            
            - jsonPath: $.PetRegistrationApplications.*.propertyId

            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdBy

            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy

            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdTime
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime

        - query: INSERT INTO eg_ptr_address(id, tenantid, doorno, latitude, longitude, buildingname, addressid, addressnumber, type, addressline1, addressline2, landmark, street, city, locality, pincode, detail, registrationid, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.address.id

            - jsonPath: $.PetRegistrationApplications.*.address.tenantId

            - jsonPath: $.PetRegistrationApplications.*.address.doorNo

            - jsonPath: $.PetRegistrationApplications.*.address.latitude

            - jsonPath: $.PetRegistrationApplications.*.address.longitude

            - jsonPath: $.PetRegistrationApplications.*.address.buildingName

            - jsonPath: $.PetRegistrationApplications.*.address.addressId

            - jsonPath: $.PetRegistrationApplications.*.address.addressNumber

            - jsonPath: $.PetRegistrationApplications.*.address.type

            - jsonPath: $.PetRegistrationApplications.*.address.addressLine1

            - jsonPath: $.PetRegistrationApplications.*.address.addressLine2

            - jsonPath: $.PetRegistrationApplications.*.address.landmark

            - jsonPath: $.PetRegistrationApplications.*.address.street

            - jsonPath: $.PetRegistrationApplications.*.address.city

            - jsonPath: $.PetRegistrationApplications.*.address.locality.name

            - jsonPath: $.PetRegistrationApplications.*.address.pincode

            - jsonPath: $.PetRegistrationApplications.*.address.detail

            - jsonPath: $.PetRegistrationApplications.*.id

            - jsonPath: $.PetRegistrationApplications.*.address.createdBy

            - jsonPath: $.PetRegistrationApplications.*.address.lastModifiedBy

            - jsonPath: $.PetRegistrationApplications.*.address.createdTime

            - jsonPath: $.PetRegistrationApplications.*.address.lastModifiedTime
            
        - query: INSERT INTO eg_ptr_petdetails(id, petName, petType, breedType, petAge, petGender, clinicName, doctorName, lastVaccineDate, vaccinationNumber, petDetailsId, petColor, adoptionDate, birthDate, identificationMark) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.petDetails.id

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petName

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petType

            - jsonPath: $.PetRegistrationApplications.*.petDetails.breedType

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petAge

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petGender

            - jsonPath: $.PetRegistrationApplications.*.petDetails.clinicName

            - jsonPath: $.PetRegistrationApplications.*.petDetails.doctorName

            - jsonPath: $.PetRegistrationApplications.*.petDetails.lastVaccineDate
            
            - jsonPath: $.PetRegistrationApplications.*.petDetails.vaccinationNumber

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petDetailsId

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petColor

            - jsonPath: $.PetRegistrationApplications.*.petDetails.adoptionDate

            - jsonPath: $.PetRegistrationApplications.*.petDetails.birthDate

            - jsonPath: $.PetRegistrationApplications.*.petDetails.identificationMark
        
            
        - query: INSERT INTO eg_ptr_applicationdocuments( id, tenantId, documentType, filestoreId, documentUid, petApplicationId, active, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*.documents.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.id

            - jsonPath: $.PetRegistrationApplications.*.tenantId
 
            - jsonPath: $.PetRegistrationApplications.*.documentType

            - jsonPath: $.PetRegistrationApplications.*.filestoreId

            - jsonPath: $.PetRegistrationApplications.*.documentUid
            
            - jsonPath: $.PetRegistrationApplications.*.[?({id} in @.documents[*].id)].id
             
            - jsonPath: $.PetRegistrationApplications.*.active
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdBy
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdTime
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime


    - version: 1.0
      description: Update Status for expired application
      fromTopic: expire-ptr-application
      isTransaction: true
      queryMaps:
        - query: UPDATE eg_ptr_registration SET status = ? WHERE applicationnumber=?;
          basePath: PetRegistrationApplications.*
          jsonMaps:

            - jsonPath: $.PetRegistrationApplications.*.status

            - jsonPath: $.PetRegistrationApplications.*.applicationnumber
    
    - version: 1.0
      description: Update Pet Registration application
      fromTopic: update-ptr-application
      isTransaction: true
      queryMaps:
        - query: UPDATE eg_ptr_registration SET status = ?, pettoken = ?, lastmodifiedby = ?, lastmodifiedtime = ?  WHERE id=?;
          basePath: PetRegistrationApplications.*
          jsonMaps:

            - jsonPath: $.PetRegistrationApplications.*.status

            - jsonPath: $.PetRegistrationApplications.*.petToken

            - jsonPath: $.PetRegistrationApplications.*.lastModifiedBy

            - jsonPath: $.PetRegistrationApplications.*.lastmodifiedtime

            - jsonPath: $.PetRegistrationApplications.*.id

    - version: 1.0
      description: Persists Renew Pet details in tables
      fromTopic: renew-ptr-application
      isTransaction: true	
      queryMaps:

        - query: INSERT INTO eg_ptr_registration(id,tenantid,applicationnumber,applicantName,fathername,mobileNumber,emailId,applicationType,validityDate,status,expireFlag,petToken,previousApplicationNumber,propertyId,createdby,lastmodifiedby,createdtime,lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.id

            - jsonPath: $.PetRegistrationApplications.*.tenantId

            - jsonPath: $.PetRegistrationApplications.*.applicationNumber
            
            - jsonPath: $.PetRegistrationApplications.*.applicantName
          
            - jsonPath: $.PetRegistrationApplications.*.fatherName
            
            - jsonPath: $.PetRegistrationApplications.*.mobileNumber
            
            - jsonPath: $.PetRegistrationApplications.*.emailId
            
            - jsonPath: $.PetRegistrationApplications.*.applicationType

            - jsonPath: $.PetRegistrationApplications.*.validityDate

            - jsonPath: $.PetRegistrationApplications.*.status

            - jsonPath: $.PetRegistrationApplications.*.expireFlag

            - jsonPath: $.PetRegistrationApplications.*.petToken

            - jsonPath: $.PetRegistrationApplications.*.previousApplicationNumber

            - jsonPath: $.PetRegistrationApplications.*.propertyId
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdBy

            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy

            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdTime
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime

        - query: INSERT INTO eg_ptr_address(id, tenantid, doorno, latitude, longitude, buildingname, addressid, addressnumber, type, addressline1, addressline2, landmark, street, city, locality, pincode, detail, registrationid, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.address.id

            - jsonPath: $.PetRegistrationApplications.*.address.tenantId

            - jsonPath: $.PetRegistrationApplications.*.address.doorNo

            - jsonPath: $.PetRegistrationApplications.*.address.latitude

            - jsonPath: $.PetRegistrationApplications.*.address.longitude

            - jsonPath: $.PetRegistrationApplications.*.address.buildingName

            - jsonPath: $.PetRegistrationApplications.*.address.addressId

            - jsonPath: $.PetRegistrationApplications.*.address.addressNumber

            - jsonPath: $.PetRegistrationApplications.*.address.type

            - jsonPath: $.PetRegistrationApplications.*.address.addressLine1

            - jsonPath: $.PetRegistrationApplications.*.address.addressLine2

            - jsonPath: $.PetRegistrationApplications.*.address.landmark

            - jsonPath: $.PetRegistrationApplications.*.address.street

            - jsonPath: $.PetRegistrationApplications.*.address.city

            - jsonPath: $.PetRegistrationApplications.*.address.locality.name

            - jsonPath: $.PetRegistrationApplications.*.address.pincode

            - jsonPath: $.PetRegistrationApplications.*.address.detail

            - jsonPath: $.PetRegistrationApplications.*.id

            - jsonPath: $.PetRegistrationApplications.*.address.createdBy

            - jsonPath: $.PetRegistrationApplications.*.address.lastModifiedBy

            - jsonPath: $.PetRegistrationApplications.*.address.createdTime

            - jsonPath: $.PetRegistrationApplications.*.address.lastModifiedTime
            
        - query: INSERT INTO eg_ptr_petdetails(id, petName, petType, breedType, petAge, petGender, clinicName, doctorName, lastVaccineDate, vaccinationNumber, petDetailsId, petColor, adoptionDate, birthDate, identificationMark) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.petDetails.id

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petName

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petType

            - jsonPath: $.PetRegistrationApplications.*.petDetails.breedType

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petAge

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petGender

            - jsonPath: $.PetRegistrationApplications.*.petDetails.clinicName

            - jsonPath: $.PetRegistrationApplications.*.petDetails.doctorName

            - jsonPath: $.PetRegistrationApplications.*.petDetails.lastVaccineDate
            
            - jsonPath: $.PetRegistrationApplications.*.petDetails.vaccinationNumber

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petDetailsId

            - jsonPath: $.PetRegistrationApplications.*.petDetails.petColor

            - jsonPath: $.PetRegistrationApplications.*.petDetails.adoptionDate

            - jsonPath: $.PetRegistrationApplications.*.petDetails.birthDate

            - jsonPath: $.PetRegistrationApplications.*.petDetails.identificationMark
        
            
        - query: INSERT INTO eg_ptr_applicationdocuments( id, tenantId, documentType, filestoreId, documentUid, petApplicationId, active, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: PetRegistrationApplications.*.documents.*
          jsonMaps:
            - jsonPath: $.PetRegistrationApplications.*.id

            - jsonPath: $.PetRegistrationApplications.*.tenantId
 
            - jsonPath: $.PetRegistrationApplications.*.documentType

            - jsonPath: $.PetRegistrationApplications.*.filestoreId

            - jsonPath: $.PetRegistrationApplications.*.documentUid
            
            - jsonPath: $.PetRegistrationApplications.*.[?({id} in @.documents[*].id)].id
             
            - jsonPath: $.PetRegistrationApplications.*.active
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdBy
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedBy
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.createdTime
            
            - jsonPath: $.PetRegistrationApplications.*.auditDetails.lastModifiedTime

        - query: UPDATE eg_ptr_registration SET status = 'RENEWED' WHERE applicationNumber=?;
          basePath: PetRegistrationApplications.*
          jsonMaps:

            - jsonPath: $.PetRegistrationApplications.*.previousApplicationNumber