SearchDefinitions:
  moduleName: chb-services
  summary: Chb Services Inbox API
  version: 1.0.0
  definitions:
    - name: inboxchbsearch
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(chb.booking_no),pi.createdtime from 
		      eg_chb_booking_detail as chb
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = chb.booking_no
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = chb.booking_no GROUP BY wf.businessid)
          order by pi.createdtime asc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: chb.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: chb.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: chb.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.bookingId
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"HallApplication": []}
        outJsonPath: $.HallApplication
        responseInfoPath: $.ResponseInfo
    - name: inboxchbsearchdesc
      query:
        baseQuery: Select row_to_json(result) from
          (
          select DISTINCT(chb.booking_no),pi.createdtime from 
		      eg_chb_booking_detail as chb
          INNER JOIN eg_wf_processinstance_v2 pi ON pi.businessid = chb.booking_no
          $where
          AND pi.createdtime IN (select max(createdtime) from eg_wf_processinstance_v2 wf where wf.businessid = chb.booking_no GROUP BY wf.businessid)
          order by pi.createdtime desc $pagination
          ) result
        groupBy:
        orderBy:
      searchParams:
        condition: AND
        params:
          - name: chb.tenantid
            isMandatory: true
            jsonPath: $.searchCriteria.tenantId
          - name: chb.id
            isMandatory: false
            jsonPath: $.searchCriteria.id
          - name: chb.booking_no
            isMandatory: false
            jsonPath: $.searchCriteria.requestId
          - name: pi.businessservice
            isMandatory: false
            jsonPath: $.searchCriteria.businessservice
        pagination:
          noOfRecords: $.searchCriteria.noOfRecords
          offset: $.searchCriteria.offset

      output:
        jsonFormat: {"ResponseInfo": {},"HallApplication": []}
        outJsonPath: $.HallApplication
        responseInfoPath: $.ResponseInfo